### ISSUE TITLE
Experiencing delays and "not responding"

### ISSUE THREAD

**Issue by oskargargas** [WhiteMagic/JoystickGremlin#194]
Hello,

I'm using R.12 after recent upgrade from R.10 (after few months of not flying). I see delays in forwarding input from hardware through gremlin to vjoy (and then to DCS). From time to time Gremlin hangs with "not responding" notice.

How can I check, log and diagnose if it's something with my system or something in Gremlin?

Windows 10 x64, neweest vJoy (installed yesterday), Intel, nVidia, 16GB of RAM, don't know if anything of this matters. ;)

Regards
Oskar

**Comment by WhiteMagic** [comment]
This definitely sounds like something is going wrong, as nothing Gremlin does really is computationally expensive. You can find a log in %userprofile%/Joystick Gremlin/system.log

One possible source could be that vJoy is "losing" the devices every now and then which might show up in the log. Another possible issue is windows having fun with devices. I every now and then have an issue where joy.cpl will take ages to open which is due to windows wanting to treat a device as a stick when it's not and timing out or something. So if you have issues like that that occur in the middle of Gremlin being active that could cause issues.

Are you using any obscure hardware that could possibly be read badly by Gremlin and thus create stalls?

**Comment by oskargargas** [comment]
Thanks for the info. 

I don't think I have any obscure hardware attached. I use TM Warthog Joystic + Throttle, MFG Crosswind pedals, Saitek TQC, Switch Panel and Multi Panel (those I'm using with DCS Flight Panels).

I didn't see anything strange in the log. Besides "WARNING Identifier for non existent device created" related to TM Cougar Throttle (+ TUSBA R2) which I don't use right now. I commented this out from the config file.

In addition I cleaned up my system a bit. Uninstalled Visual Studio, IIS, MS SQL as I don't use it on this machine anymore. I also uninstalled Windows Driver Kit which I looked into some time ago because of HidGuardian. I also cleaned and reinstall HidGuardian as described here: https://github.com/WhiteMagic/JoystickGremlin/issues/191

For now everything looks ok. I'll test for few days and I'll let know if problem occurs again.

**Comment by oskargargas** [comment]
Or... few minutes. It just happened again. 

The only thing I see in log is "INFO Found regex match in  for ..." related with profile switching basend on current application. So I turned this option off as I don't use it. We'll see.

Also, from time to time, I have problem with Tempo mapped button. But I don't think it's related. When it happens I see error message
`ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\event_handler.py", line 481, in process_event
   File "gremlin\execution_graph.py", line 76, in __call__
   File "gremlin\execution_graph.py", line 172, in process_event
   File "container_plugins\tempo\__init__.py", line 257, in process_event
    self.timer.cancel()
 AttributeError: 'NoneType' object has no attribute 'cancel'
`
And both buttons from tempo activate (when should only one, short press). Profile restart helps for that.

**Comment by WhiteMagic** [comment]
By the sound of things it's not an issue with vJoy devices being lost, or at least not severe enough for log entries. One thing you could try to see if this is something related to one of your devices is to unplug one at a time or plug them in one after the other and see when the issue starts again. Though that only makes sense to try if the issue happens quite quickly.

The tempo container issue should not cause this, though with timers and threads it's not always easy to say if they do crazy things. I'll take a look at that error anyway.

**Comment by rennerdo30** [comment]
Lately I have the same problem:

```
2024-12-22 20:08:48       INFO Gremlin UI launching
2024-12-22 20:19:07      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\event_handler.py", line 489, in process_event
   File "gremlin\execution_graph.py", line 76, in __call__
   File "gremlin\execution_graph.py", line 172, in process_event
   File "container_plugins\tempo\__init__.py", line 257, in process_event
    self.timer.cancel()
 AttributeError: 'NoneType' object has no attribute 'cancel'
```

**Comment by WhiteMagic** [comment]
Are you by chance using a Macro inside the long press and triggering the action at a high rate? Someone else recently found that this combination can cause this issue. I haven't figured out how that plays together as the part that causes the exception shouldn't logically be reachable in this invalid state.

Though this should be a separate issue as the original one wasn't linked to this particular issue.

**Comment by rennerdo30** [comment]
This is the problematic mapping in my case:
![image](https://github.com/user-attachments/assets/0dffe21c-c58e-42d8-8a20-e111160525c8)

The bindings are from https://ko-fi.com/s/db31a35bb0 and are for Star Citizen.
Most of the time, when I hold the "Button 3" Joystick Gremlin will freeze. Sometimes it also throws the error as mentioned above.

**Comment by WhiteMagic** [comment]
Hm that's a different scneario then. In the binding nothing is very out of the ordinary, only that cycle modes with one mode is kind of redundant.

**Comment by FlameSoulis** [comment]
Bumping for the same situation. Using a rudder merge and also noticing that it ONLY happens for Star Citizen...

Logs do not show anything interesting, and even attempting to shift priority and adjust threads doesn't fix anything.

Anything special I can do to help diagnose the issue? I'm no stranger to Python debugging.

**Comment by PattrnData** [comment]
Having the same issue as this did any of you find a solution?

**Comment by WhiteMagic** [comment]
R14 changed quite a few things, and the input library also got some tiny changes. Would be good to know if these issues still persist.
