### ISSUE TITLE
Crash on opening Gremlin

### ISSUE THREAD

**Issue by hokie17** [WhiteMagic/JoystickGremlin#198]
I can't get JG to launch at all.  I have one vJoy device setup, but this is my log.  Can anyone help me out?

`2019-03-29 21:13:06      DEBUG --------------------------------------------------------------------------------
2019-03-29 21:13:06      DEBUG 2019-03-29 21:13
2019-03-29 21:13:06      DEBUG Starting Joystick Gremlin R12
2019-03-29 21:13:06      DEBUG --------------------------------------------------------------------------------
2019-03-29 21:13:06       INFO Initializing joystick devices
2019-03-29 21:13:06      DEBUG 4 joysticks detected
2019-03-29 21:13:06      DEBUG Added: name=Saitek Pro Flight Combat Rudder Pedals windows_id=3 hardware_id=111347556
2019-03-29 21:13:06      DEBUG Added: name=Joystick - HOTAS Warthog windows_id=2 hardware_id=72287234
2019-03-29 21:13:06      DEBUG Added: name=vJoy Device windows_id=1 hardware_id=305446573
2019-03-29 21:13:06      DEBUG Added: name=Throttle - HOTAS Warthog windows_id=0 hardware_id=72287236
2019-03-29 21:13:06      DEBUG vJoy windows id 1: (8, 128, 1)
2019-03-29 21:13:06      DEBUG vjoy id 1: (8, 128, 0) - ERROR - vJoy device exists SDL is missing
2019-03-29 21:13:06      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1310, in <module>
   File "gremlin\joystick_handling.py", line 356, in joystick_devices_initialization
 gremlin.error.GremlinError: 'Unable to match vJoy devices to windows devices.'`

**Comment by WhiteMagic** [comment]
I've seen this particular error typically occur when the vJoy device has the POV Hat Switch set to "4 Directions" instead of "Continuous". I'd check that first, if that's not the problem then we'll have to dig further.

**Comment by hokie17** [comment]
Thanks, that did it.  Now I just have to learn the program!

I don't suppose there's a way to make the mouse move to a specific spot on the screen by pressing a joystick button, is there?

**Comment by WhiteMagic** [comment]
No there isn't, while technically it's rather simple to do Gremlin doesn't support it mainly for two reason. For one most games will not react to such inputs for various reasons and second it makes it less likely that Gremlin gets considered as a cheat tool by anti-cheat software.

**Comment by hokie17** [comment]
Thanks. I suppose I can use a macro to move it to one corner and a second macro to move it to the spot I want. Sound like that would work?

**Comment by WhiteMagic** [comment]
Yeah you can send any relative motions you want, so sending a very large movement should put you at the edge, depending on how the game handles large mouse deltas.

**Comment by hokie17** [comment]
Thanks for your help!
