### ISSUE TITLE
Uncaught Exception: Traceback 

### ISSUE THREAD

**Issue by suTrust** [WhiteMagic/JoystickGremlin#210]
I'm having an issue that is similar to this one:
https://github.com/WhiteMagic/JoystickGremlin/issues/147

Running R13.1b2, on an i5 with Windows 10. 
Using Saitek x52
This may have something to do with Windows security settings.
I was having an issue thwere the application would launch, get suspended and quietly die without alert. I added it as an exception in Windows Defender, and now I'm getting the above error.

019-04-19 15:07:29      DEBUG --------------------------------------------------------------------------------
2019-04-19 15:07:29      DEBUG 2019-04-19 15:07
2019-04-19 15:07:29      DEBUG Starting Joystick Gremlin R13.1
2019-04-19 15:07:29      DEBUG --------------------------------------------------------------------------------
2019-04-19 15:07:30       INFO Initializing joystick devices
2019-04-19 15:07:30      DEBUG 2 joysticks detected
2019-04-19 15:07:30      DEBUG Added: name=Saitek X52 Pro Flight Control System guid={D0C2BE50-0EB2-11E6-8007-444553540000}
2019-04-19 15:07:30      DEBUG Added: name=vJoy Device guid={454A50A0-CB71-11E6-8003-444553540000}
2019-04-19 15:07:30      DEBUG vJoy guid={454A50A0-CB71-11E6-8003-444553540000}: (8, 32, 0)
2019-04-19 15:07:30      DEBUG vjoy id 9: (8, 32, 0) - MATCH
2019-04-19 15:07:30      ERROR Requested vJoy device is not available - vid: 9
2019-04-19 15:07:30      ERROR Requested vJoy device is not available - vid: 9
NoneType: None
2019-04-19 15:07:30      ERROR Failed accessing vJoy id=9, error is: 'Requested vJoy device is not available - vid: 9'
2019-04-19 15:07:30      DEBUG vJoy id 9 can't be acquired
2019-04-19 15:07:30       INFO Checking vJoy installation
2019-04-19 15:07:30       INFO Initializing plugins
2019-04-19 15:07:30      DEBUG Loaded: cycle-modes
2019-04-19 15:07:30      DEBUG Loaded: description
2019-04-19 15:07:30      DEBUG Loaded: macro
2019-04-19 15:07:30      DEBUG Loaded: map-to-keyboard
2019-04-19 15:07:30      DEBUG Loaded: map-to-mouse
2019-04-19 15:07:30      DEBUG Loaded: noop
2019-04-19 15:07:30      DEBUG Loaded: pause
2019-04-19 15:07:30      DEBUG Loaded: play-sound
2019-04-19 15:07:30      DEBUG Loaded: previous-mode
2019-04-19 15:07:30      DEBUG Loaded: remap
2019-04-19 15:07:30      DEBUG Loaded: response-curve
2019-04-19 15:07:30      DEBUG Loaded: resume
2019-04-19 15:07:30      DEBUG Loaded: split-axis
2019-04-19 15:07:30      DEBUG Loaded: switch-mode
2019-04-19 15:07:30      DEBUG Loaded: temporary-mode-switch
2019-04-19 15:07:31      DEBUG Loaded: text-to-speech
2019-04-19 15:07:31      DEBUG Loaded: toggle-pause
2019-04-19 15:07:31      DEBUG Loaded: basic
2019-04-19 15:07:31      DEBUG Loaded: chain
2019-04-19 15:07:31      DEBUG Loaded: double_tap
2019-04-19 15:07:31      DEBUG Loaded: hat_buttons
2019-04-19 15:07:31      DEBUG Loaded: smart_toggle
2019-04-19 15:07:31      DEBUG Loaded: tempo
2019-04-19 15:07:31      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1311, in <module>
   File "joystick_gremlin.py", line 119, in __init__
   File "joystick_gremlin.py", line 440, in new_profile
   File "gremlin\profile.py", line 1330, in initialize_joystick_device
 IndexError: list index out of range

**Comment by WhiteMagic** [comment]
I'm not sure if your issue is the same as the one in #210 but it seems possible, if you want you can use the same replacement library to provide the additional debug information which hopefully helps me narrow down what's going wrong.

I can easily fix the issue with Gremlin crashing, but it might just hide the symptom and not fix the root cause.
