### ISSUE TITLE
Joystick Gremlin wont start

### ISSUE THREAD

**Issue by FlyingBeard** [WhiteMagic/JoystickGremlin#220]
I get this error message in the log file:

2019-05-29 18:26:01      DEBUG --------------------------------------------------------------------------------
2019-05-29 18:26:01      DEBUG 2019-05-29 18:26
2019-05-29 18:26:01      DEBUG Starting Joystick Gremlin R13.1
2019-05-29 18:26:01      DEBUG --------------------------------------------------------------------------------
2019-05-29 18:26:01       INFO Initializing joystick devices
2019-05-29 18:26:01      DEBUG 5 joysticks detected
2019-05-29 18:26:01      DEBUG Added: name=Saitek Pro Flight Rudder Pedals guid={AA9CF4E0-E397-11E8-800A-444553540000}
2019-05-29 18:26:01      DEBUG Added: name=Logitech G13 Joystick guid={56932C60-E398-11E8-8003-444553540000}
2019-05-29 18:26:01      DEBUG Added: name=F16 MFD 2 guid={8114E570-E396-11E8-8002-444553540000}
2019-05-29 18:26:01      DEBUG Added: name=Controller (Xbox One For Windows) guid={31B8B540-E762-11E8-8001-444553540000}
2019-05-29 18:26:01      DEBUG Added: name=F16 MFD 1 guid={8114BE60-E396-11E8-8001-444553540000}
2019-05-29 18:26:01      DEBUG vjoy id 1: (8, 64, 4) - ERROR - vJoy device exists but DILL does not see it
2019-05-29 18:26:01      ERROR Unable to match vJoy devices to windows devices.
NoneType: None
2019-05-29 18:26:01      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1271, in <module>
   File "gremlin\joystick_handling.py", line 304, in joystick_devices_initialization
 gremlin.error.GremlinError: 'Unable to match vJoy devices to windows devices.'

**Comment by WhiteMagic** [comment]
That's odd, the input library is not seeing the vJoy device which is really really odd. Can you grab this file and run the example.exe within https://github.com/WhiteMagic/dill/releases/download/v1.2/dill_1.2.zip and see if the console window shows all the devices and post the produced debug.txt file, as that might contain some hints.

**Comment by FlyingBeard** [comment]
I think i solved, after restarting my computer I stopped getting that error. Now instead when I try to start Joystick Gremlin the window wont open, no errors nothing. after some testing I found I could get it to start sometimes if I changed the vJoy device in the vJoy configure tool and started Joystick gremlin right away afterwards. It also works if I try to start it several times, forst start nothing happens, second start I get an error message and the third time it starts but I cant see all my input devices.
Here is a log from a tripel start:

2019-05-31 14:01:42      DEBUG --------------------------------------------------------------------------------
2019-05-31 14:01:42      DEBUG 2019-05-31 14:01
2019-05-31 14:01:42      DEBUG Starting Joystick Gremlin R13.1
2019-05-31 14:01:42      DEBUG --------------------------------------------------------------------------------
2019-05-31 14:01:42       INFO Initializing joystick devices
2019-05-31 14:01:42      DEBUG 7 joysticks detected
2019-05-31 14:01:42      DEBUG Added: name=Saitek Pro Flight Rudder Pedals guid={AA9CF4E0-E397-11E8-800A-444553540000}
2019-05-31 14:01:42      DEBUG Added: name=vJoy Device guid={DF598680-8194-11E9-8002-444553540000}
2019-05-31 14:01:42      DEBUG Added: name=Logitech G13 Joystick guid={56932C60-E398-11E8-8003-444553540000}
2019-05-31 14:01:42      DEBUG Added: name=Controller (Xbox One For Windows) guid={31B8B540-E762-11E8-8001-444553540000}
2019-05-31 14:01:42      DEBUG Added: name=F16 MFD 1 guid={8114BE60-E396-11E8-8001-444553540000}
2019-05-31 14:01:42      DEBUG Added: name=X52 Professional H.O.T.A.S. guid={A0A30D40-E396-11E8-8008-444553540000}
2019-05-31 14:01:42      DEBUG Added: name=Thrustmaster Combined guid={3AFB5000-E590-11E8-8004-444553540000}
2019-05-31 14:01:42      DEBUG vJoy guid={DF598680-8194-11E9-8002-444553540000}: (8, 64, 4)
2019-05-31 14:01:42      DEBUG vjoy id 1: (8, 64, 4) - MATCH
2019-05-31 14:01:42       INFO Checking vJoy installation
2019-05-31 14:01:42       INFO Initializing plugins
2019-05-31 14:01:42      DEBUG Loaded: cycle-modes
2019-05-31 14:01:42      DEBUG Loaded: description
2019-05-31 14:01:42      DEBUG Loaded: macro
2019-05-31 14:01:42      DEBUG Loaded: map-to-keyboard
2019-05-31 14:01:42      DEBUG Loaded: map-to-mouse
2019-05-31 14:01:42      DEBUG Loaded: noop
2019-05-31 14:01:42      DEBUG Loaded: pause
2019-05-31 14:01:44      DEBUG Loaded: play-sound
2019-05-31 14:01:44      DEBUG Loaded: previous-mode
2019-05-31 14:01:44      DEBUG Loaded: remap
2019-05-31 14:01:44      DEBUG Loaded: response-curve
2019-05-31 14:01:44      DEBUG Loaded: resume
2019-05-31 14:01:44      DEBUG Loaded: split-axis
2019-05-31 14:01:44      DEBUG Loaded: switch-mode
2019-05-31 14:01:44      DEBUG Loaded: temporary-mode-switch
2019-05-31 14:01:44      DEBUG Loaded: text-to-speech
2019-05-31 14:01:44      DEBUG Loaded: toggle-pause
2019-05-31 14:01:44      DEBUG Loaded: basic
2019-05-31 14:01:44      DEBUG Loaded: chain
2019-05-31 14:01:44      DEBUG Loaded: double_tap
2019-05-31 14:01:45      DEBUG Loaded: hat_buttons
2019-05-31 14:01:45      DEBUG Loaded: smart_toggle
2019-05-31 14:01:45      DEBUG Loaded: tempo
2019-05-31 14:01:45      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1311, in <module>
   File "joystick_gremlin.py", line 119, in __init__
   File "joystick_gremlin.py", line 440, in new_profile
   File "gremlin\profile.py", line 1330, in initialize_joystick_device
 IndexError: list index out of range

2019-05-31 14:01:51      DEBUG --------------------------------------------------------------------------------
2019-05-31 14:01:51      DEBUG 2019-05-31 14:01
2019-05-31 14:01:51      DEBUG Starting Joystick Gremlin R13.1
2019-05-31 14:01:51      DEBUG --------------------------------------------------------------------------------
2019-05-31 14:01:51       INFO Initializing joystick devices
2019-05-31 14:01:51      DEBUG 3 joysticks detected
2019-05-31 14:01:51      DEBUG Added: name=Saitek Pro Flight Rudder Pedals guid={AA9CF4E0-E397-11E8-800A-444553540000}
2019-05-31 14:01:51      DEBUG Added: name=vJoy Device guid={DF598680-8194-11E9-8002-444553540000}
2019-05-31 14:01:51      DEBUG Added: name=Logitech G13 Joystick guid={56932C60-E398-11E8-8003-444553540000}
2019-05-31 14:01:51      DEBUG vJoy guid={DF598680-8194-11E9-8002-444553540000}: (8, 64, 4)
2019-05-31 14:01:51      DEBUG vjoy id 1: (8, 64, 4) - MATCH
2019-05-31 14:01:51       INFO Checking vJoy installation
2019-05-31 14:01:51       INFO Initializing plugins
2019-05-31 14:01:51      DEBUG Loaded: cycle-modes
2019-05-31 14:01:51      DEBUG Loaded: description
2019-05-31 14:01:51      DEBUG Loaded: macro
2019-05-31 14:01:51      DEBUG Loaded: map-to-keyboard
2019-05-31 14:01:51      DEBUG Loaded: map-to-mouse
2019-05-31 14:01:51      DEBUG Loaded: noop
2019-05-31 14:01:51      DEBUG Loaded: pause
2019-05-31 14:01:52      DEBUG Loaded: play-sound
2019-05-31 14:01:52      DEBUG Loaded: previous-mode
2019-05-31 14:01:52      DEBUG Loaded: remap
2019-05-31 14:01:52      DEBUG Loaded: response-curve
2019-05-31 14:01:52      DEBUG Loaded: resume
2019-05-31 14:01:52      DEBUG Loaded: split-axis
2019-05-31 14:01:52      DEBUG Loaded: switch-mode
2019-05-31 14:01:52      DEBUG Loaded: temporary-mode-switch
2019-05-31 14:01:52      DEBUG Loaded: text-to-speech
2019-05-31 14:01:52      DEBUG Loaded: toggle-pause
2019-05-31 14:01:52      DEBUG Loaded: basic
2019-05-31 14:01:52      DEBUG Loaded: chain
2019-05-31 14:01:52      DEBUG Loaded: double_tap
2019-05-31 14:01:52      DEBUG Loaded: hat_buttons
2019-05-31 14:01:52      DEBUG Loaded: smart_toggle
2019-05-31 14:01:52      DEBUG Loaded: tempo
2019-05-31 14:01:53       INFO Gremlin UI created
2019-05-31 14:01:53       INFO Gremlin UI launching

**Comment by WhiteMagic** [comment]
For some reason the input library (dill) seems to be too slow(?) at enumerating the devices and things then go bad, or alternatively you have a device which somewhat lies about the number of axes it has.

You can give the new release a go (https://github.com/WhiteMagic/JoystickGremlin/releases/tag/Release_13.2) which has a bunch of fixes with regards to the second issue. Also posting the debug.txt found in the main Gremlin folder might help (this can be somewhat big so deleting it before testing can't hurt).

**Comment by FlyingBeard** [comment]
The new version did it. It starts every time so far an finds all the input devices.
Thank you!

**Comment by WhiteMagic** [comment]
Good to hear, there probably are still some other edge cases I'll have to address as they arise.
