### ISSUE TITLE
KeyError while managing modes

### ISSUE THREAD

**Issue by doniecm** [WhiteMagic/JoystickGremlin#222]
Happens while trying to edit/rename a mode. Attached the profile.

Traceback (most recent call last):
   File "gremlin\ui\dialogs.py", line 863, in <lambda>
   File "gremlin\ui\dialogs.py", line 910, in _change_mode_inheritance
 KeyError: 'Mode 2'

2019-06-09 10:03:59      ERROR Uncaught exception:
Traceback (most recent call last):
[DCS.zip](https://github.com/WhiteMagic/JoystickGremlin/files/3269382/DCS.zip)

   File "gremlin\ui\dialogs.py", line 874, in <lambda>
   File "gremlin\ui\dialogs.py", line 937, in _rename_mode
 KeyError: 'Mode 2'

**Comment by WhiteMagic** [comment]
You seem to have found an edge case with the mode managing part, where it assumes that mode entries exist for every device. In your case that wasn't the case for the XInput controller. The bug should be relatively easy to fix, but while I do that the following XML should work without causing crashes, I simply added the missing mode entry to the offending device.

[DCS.zip](https://github.com/WhiteMagic/JoystickGremlin/files/3276421/DCS.zip)

**Comment by WhiteMagic** [comment]
Should be fixed with 8b1f5ab08a2c77bbc91c39f500d9675a3f140fba
