### ISSUE TITLE
 gremlin.error.VJoyError: 'Invalid linear index for axis lookup provided - vjoy: 1 input: 5 value: '

### ISSUE THREAD

**Issue by lukeg87** [WhiteMagic/JoystickGremlin#317]
Hi, recently had an issue with the z potentiometer on my t16000m joystick the original failed and a wire became loose, i have replaced the part with this one: [https://www.mouser.co.uk/ProductDetail/CTS-Electronic-Components/251B12T104A2NB/?qs=6E8igxPflKdliaNMymwp6A==](url)

i soldered the wires to it, the joystick reads the z axis fine in the input viewer, but now when i activate joystick gremlin, i get this error
```
---------------------------
Error
---------------------------
Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 321, in activate
   File "gremlin\code_runner.py", line 245, in start
   File "vjoy\vjoy.py", line 635, in axis
 gremlin.error.VJoyError: 'Invalid linear index for axis lookup provided - vjoy: 1 input: 5 value: '

---------------------------
OK   
---------------------------
```
[gremlin-log_and_profile.zip](https://github.com/WhiteMagic/JoystickGremlin/files/5067750/gremlin-log_and_profile.zip)

**Comment by lukeg87** [comment]
i've just read the other post regarding a similar error, creating a new profile works as expected.

Must be something in the profile which is causing the issue, ill do a comparison of the files and see if i can figure it out

**Comment by lukeg87** [comment]
i cleaned up the profile, all sorts of extra devices in there, even a second vJoy GUID, works as intended now.
