### ISSUE TITLE
Uncaught Exception: Traceback

### ISSUE THREAD

**Issue by paxoman** [WhiteMagic/JoystickGremlin#318]
Hello all, could do with a bit of help with this error, JG was working fine for a week or so now i keep getting a error which occurs when i start moving my rudder peddles at the same time as my stick.
Many Thanks James

2020-08-17 07:45:06      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 800, in _joystick_input_selection
   File "gremlin\ui\input_item.py", line 270, in select_item
   File "gremlin\ui\input_item.py", line 155, in event_to_index
 KeyError: 6

**Comment by mbzandhanna** [comment]
I'm getting the exact same error when starting Gremlin, it never opens but I see it running in task manager.. I had a couple months ago and again yesterday when I came back to try this project again starting with all new fresh vJoy-WhiteKnight-Gremlin installs.

![Joystick Gremlin Error Message](https://user-images.githubusercontent.com/69822163/90445878-41fbee80-e095-11ea-98df-02fc8d7a5e32.jpg)

[Joystick Gremlin debug.txt](https://github.com/WhiteMagic/JoystickGremlin/files/5086866/Joystick.Gremlin.debug.txt)

**Comment by WhiteMagic** [comment]
Hard to say what is the source of this problem without knowing what your profile looks like, what devices you have, and what the vJoy configuration looks like. There is a few possible things I can think of but that's just random guesses without more information.
