### ISSUE TITLE
Uncaught exception:   Traceback (most recent call last)

### ISSUE THREAD

**Issue by mbzandhanna** [WhiteMagic/JoystickGremlin#319]
I'm getting this error when starting Gremlin, it never opens but I see it running in task manager.. I had the same issue, same error a couple months ago and again yesterday when I came back to try this project again starting with all new fresh vJoy-WhiteKnight-JG installations.

![Joystick Gremlin Error Message](https://user-images.githubusercontent.com/69822163/90463004-d2025e00-e0be-11ea-9bcb-71d2a3d420c4.jpg)

2020-08-16 22:17:58      DEBUG --------------------------------------------------------------------------------
2020-08-16 22:17:58      DEBUG 2020-08-16 22:17
2020-08-16 22:17:58      DEBUG Starting Joystick Gremlin R13.3
2020-08-16 22:17:58      DEBUG --------------------------------------------------------------------------------
2020-08-16 22:18:00       INFO Initializing joystick devices
2020-08-16 22:18:00      DEBUG 3 joysticks detected
2020-08-16 22:18:00      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1269, in <module>
   File "gremlin\joystick_handling.py", line 203, in joystick_devices_initialization
   File "dill\__init__.py", line 538, in get_device_information_by_index
   File "dill\__init__.py", line 357, in __init__
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 8: invalid start byte

**Comment by mbzandhanna** [comment]
I have searched and read Issue posts for at least two hours before I posted my issue. After searching for another 30 minutes or so I stumbled on to this post by another user....

"Hi, here's what happen when I have connected a G27 shifter with an USB adapter. It doesn't appear with my other devices, and if I connect the shifter after launching JG I have no problem with it. Is there a way to "blacklist" the device for JG? I don't need to remap it. If more info are required just ask, and I try to fetch it."
![Joystick Gremlin Error Message other user shifter](https://user-images.githubusercontent.com/69822163/90464928-2f001300-e0c3-11ea-82b8-3d8ab32df673.png)

I removed every other device but I never tried starting JG with my G29 pedals disconnected because it is connected inside the PC case to the USB adapter and it is somewhat of a pain to dig out the case, open it up and go in there to unplug it. Another reason I was hesitant of going through all that is because (I'm almost certain my first attempt at JG-WK-vJoy a couple months ago did not include the pedals, I don't think I had the adapter or was using them at that time) **_I guess I was wrong, maybe I did have it at that time_**. It also doesn't appear that the Logi pedals were the main problem. From the JGdebug.txt it appeared JG was detecting/talking to the Logi pedals ok aside from the 'buffered unbuffered' part which seemed to be the same with every device. It almost appears as if vJoy & JG communicating is the issue but I really am guessing, I'm new to all this remapping stuff.

"Is there a way to "blacklist" the device for JG? I don't need to remap it.".....  Unfortunately, I do need to remap one of my pedals from an axis to button.

[2020-07-10 03:16:00.472] [debug] [info] Initializing DILL v1.3
[2020-07-10 03:16:00.570] [debug] [info] {E45AE240-C14F-11EA-8002-444553540000}: Processing device: vJoy Device
[2020-07-10 03:16:00.577] [debug] [info] Skipping device {E45AE240-C14F-11EA-8002-444553540000}, not yet fully initialized
[2020-07-10 03:16:00.592] [debug] [info] Skipping device {E45AE240-C14F-11EA-8002-444553540000}, not yet fully initialized
[2020-07-10 03:16:00.607] [debug] [info] Skipping device {E45AE240-C14F-11EA-8002-444553540000}, not yet fully initialized
[2020-07-10 03:16:00.610] [debug] [info] Device summary: vJoy Device {E45AE240-C14F-11EA-8002-444553540000}
[2020-07-10 03:16:00.610] [debug] [info] Axis=2 Buttons=1 Hats=0
[2020-07-10 03:16:00.610] [debug] [info] Axis map
[2020-07-10 03:16:00.610] [debug] [info]   linear=1 id=1
[2020-07-10 03:16:00.610] [debug] [info]   linear=2 id=6
[2020-07-10 03:16:00.610] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.610] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.610] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.610] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.610] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.610] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.611] [debug] [info] {18618C60-BE62-11EA-8001-444553540000}: Processing device: Logitech® G25 Pedals
[2020-07-10 03:16:00.612] [debug] [info] Device summary: Logitech® G25 Pedals {18618C60-BE62-11EA-8001-444553540000}
[2020-07-10 03:16:00.612] [debug] [info] Axis=3 Buttons=0 Hats=0
[2020-07-10 03:16:00.612] [debug] [info] Axis map
[2020-07-10 03:16:00.612] [debug] [info]   linear=1 id=4
[2020-07-10 03:16:00.612] [debug] [info]   linear=2 id=5
[2020-07-10 03:16:00.612] [debug] [info]   linear=3 id=6
[2020-07-10 03:16:00.612] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.612] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.612] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.612] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.612] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.619] [debug] [info] {803CD0F0-B611-11EA-8006-444553540000}: Processing device: Razer Orbweaver Chroma
[2020-07-10 03:16:00.620] [debug] [info] Device summary: Razer Orbweaver Chroma {803CD0F0-B611-11EA-8006-444553540000}
[2020-07-10 03:16:00.620] [debug] [info] Axis=6 Buttons=24 Hats=1
[2020-07-10 03:16:00.620] [debug] [info] Axis map
[2020-07-10 03:16:00.620] [debug] [info]   linear=1 id=1
[2020-07-10 03:16:00.620] [debug] [info]   linear=2 id=2
[2020-07-10 03:16:00.620] [debug] [info]   linear=3 id=3
[2020-07-10 03:16:00.620] [debug] [info]   linear=4 id=4
[2020-07-10 03:16:00.620] [debug] [info]   linear=5 id=5
[2020-07-10 03:16:00.620] [debug] [info]   linear=6 id=6
[2020-07-10 03:16:00.620] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.620] [debug] [info]   linear=0 id=0
[2020-07-10 03:16:00.623] [debug] [error] {18618C60-BE62-11EA-8001-444553540000}: Attempted to read buffered device data from a device that is not buffered. (DIERR_NOTBUFFERED)
[2020-07-10 03:16:00.623] [debug] [error] {18618C60-BE62-11EA-8001-444553540000} Failed reading device in buffered mode, falling back to polling, Attempted to read buffered device data from a device that is not buffered. (DIERR_NOTBUFFERED)
[2020-07-10 03:16:00.623] [debug] [error] {803CD0F0-B611-11EA-8006-444553540000}: Attempted to read buffered device data from a device that is not buffered. (DIERR_NOTBUFFERED)
[2020-07-10 03:16:00.623] [debug] [error] {803CD0F0-B611-11EA-8006-444553540000} Failed reading device in buffered mode, falling back to polling, Attempted to read buffered device data from a device that is not buffered. (DIERR_NOTBUFFERED)
[2020-07-10 03:16:00.715] [debug] [info] Setting device change callback
[2020-07-10 03:16:00.715] [debug] [info] Setting event callback
[2020-07-10 03:37:47.737] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: Access to the device has been lost. It must be re-acquired. (DIERR_INPUTLOST)
[2020-07-10 03:37:47.753] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, Access to the device has been lost. It must be re-acquired. (DIERR_INPUTLOST)
[2020-07-10 03:37:47.753] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.768] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.768] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.783] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.783] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.799] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.799] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.814] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.814] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.830] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.830] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.845] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.845] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.861] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.861] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.876] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.876] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.891] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000} Polling failed, The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)
[2020-07-10 03:37:47.891] [debug] [error] {E45AE240-C14F-11EA-8002-444553540000}: The operation cannot be performed unless the device is acquired. (DIERR_NOTACQUIRED)


**I guess I will go in there, disconnect the pedals and see is it makes any difference. If I have positive results I will report them here asap.**

**Comment by WhiteMagic** [comment]
No Gremlin doesn't have a way of blacklisting devices, at least not in the way you're after. Given the errors, it seems likely that the (r) symbol is tripping the codec, which is rather odd given it's just UTF. What is more concerning in that log though is that this claims that the vJoy device cannot be read which should not happen and could possibly cause all sorts of issues.

**Comment by mbzandhanna** [comment]
Thanks for the response,

I was not asking about blacklisting devices, that is in another thread I found that had the same error message at startup.

So, I can open JSG if I unplug my pedals first. It shows my vJoy device and doesn't crash, JSG also seems to be ok if I plug my pedals back in after starting it but it doesn't show the pedals as a device and I don't know how to refresh it or make it show the pedals. If I close JSG and reopen when the pedals are plugged in I get that same error message again. I basically want to use JSG/vJoy for my pedals and Razer Keypad to start off with. I'm ok with my two joysticks and Keyboard not going through JSG/vJoy/HidGaurdian and being seen by Star Citizen unless there are still issues with binding conflicts then I'll map them through also but right now I am having a hard time just getting the Keypad and Pedals setup, I cannot figure out why the pedals error JSG and how to get them recognized when plugging in after startup.

Thanks....

![JSG a](https://user-images.githubusercontent.com/69822163/91647176-8def5180-ea0c-11ea-984e-c33e266b5a47.jpg)
![JSG b](https://user-images.githubusercontent.com/69822163/91647178-8def5180-ea0c-11ea-8c4b-79081b96d6f2.jpg)

**Comment by mbzandhanna** [comment]
The person with the other thread was asking about blacklisting because he doesn't need to remap his pedals. I wish I could say the same but I do need to remap my middle pedal from an axis to a switch.

**Comment by WhiteMagic** [comment]
I suspect that something about the pedals is tripping the input library up. Can you drop the debug.txt file that exists inside the joystick gremlin folder in here? That should give some clues about what that library is thinking. You can also try replacing the `dill.dll` file in the joystick gremlin folder with this one here which fixed a specific issue which isn't exactly related to this (at least not as far as I can tell but can't hurt trying).

[dill_1_3.zip](https://github.com/WhiteMagic/JoystickGremlin/files/5146736/dill_1_3.zip)

**Comment by barcamek** [comment]
I had the same issues with my pedals. 
The problem was caused by the device name. In my case "Logitech®Driving Force™Pro Pedals"
After removing ® and ™ from the device name in the windows registry, Joystick Gremlin works again.
Maybe this helps solving your problems.

**Comment by mbzandhanna** [comment]
Thanks barcamek and whitemagic. I've been crazy busy with work and some other things and haven't had a chance to do much related to this. I did change the name in Reg but haven't tested it yet. If that doesn't resolve my issues I will be doing your suggestions whitemagic. I was thinking the problems might be caused by the adapter as it's programmable and has it's own memory. I'm hoping just removing @ does the trick.

**Comment by McNutty** [comment]
Any chance that this might be looked into? Just got a Leo Bodnar cable for my Logitech Pedals, and they are now showing as "Logitech® G25 Pedals". The "registered" sign (byte `0xae`) is tripping up the start of Joystick Gremlin at this line: `self.name = data.name.decode("utf-8")`

I've managed to change the "Description" and "Friendly Name" of the device in the registry editor, but can't seem to find a way to change the actual Device Name, so the proposed workaround is not working for me unfortunately.

I'm no python developer and might be on thin ice here, but it seems that the ®-symbol is encoded with windows-1252 encoding, and thus cannot be decoded with utf-8. Maybe it's ok to just ignore "bad" unicode characters if it is only for display purposes? This change would do it then: `self.name = data.name.decode("utf-8", "ignore")`

Would love some feedback on this (or even better a fix :)), absolutely love the application and I'm so close to the perfect setup for Star Citizen! :)

/Martin

**Comment by WhiteMagic** [comment]
This will be fixed eventually with R14 but not ever in any R13 derived variant as I'm not touching that code base anymore to be able to make any progress at all.

**Comment by McNutty** [comment]
Ok, thanks for the quick answer. Looking forward to r14 then! 👍

**Comment by harf4ng** [comment]
I have the exact same issue. Sometimes it was fixed by restarting computer, but today not anymore.
Unsure what causes the issue.
Any ETA for the r14?
Can't live without joystick gremlin anymore ^^

**Comment by TheEDFLegacy** [comment]
> Any chance that this might be looked into? Just got a Leo Bodnar cable for my Logitech Pedals, and they are now showing as "Logitech® G25 Pedals". The "registered" sign (byte `0xae`) is tripping up the start of Joystick Gremlin at this line: `self.name = data.name.decode("utf-8")`
> 
> I've managed to change the "Description" and "Friendly Name" of the device in the registry editor, but can't seem to find a way to change the actual Device Name, so the proposed workaround is not working for me unfortunately.
> 
> I'm no python developer and might be on thin ice here, but it seems that the ®-symbol is encoded with windows-1252 encoding, and thus cannot be decoded with utf-8. Maybe it's ok to just ignore "bad" unicode characters if it is only for display purposes? This change would do it then: `self.name = data.name.decode("utf-8", "ignore")`
> 
> Would love some feedback on this (or even better a fix :)), absolutely love the application and I'm so close to the perfect setup for Star Citizen! :)
> 
> /Martin

I ended up finding a solution under a StackOverflow post - and this will likely answer the cause of this bug. In short, JoystickGremlin doesn't understand special characters (such as the copyright symbol that LeoBednar added to their driver names).

If you go to HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\ in your registry, and remove the Copyright symbol from the OEMName field of each affected device, JoystickGremlin should work normally.

As for the developers of JoystickGremlin itself, adding basic special character support (namely Copyright and TradeMark symbols) should solve this issue.

**Comment by WhiteMagic** [comment]
That's not truly what causes the problem and creating some special character list won't help either. The problem is that the UTF parsing chain somewhere in Gremlin makes a mistake and then gets confused with those characters that are obviously in UTF. So that is what needs fixing as anything else is just a bandaid that would break if someone has a device with a German umlaut, a Chinese character, etc.

**Comment by loatman** [comment]
I'm having this same issue except the only device currently plugged is my mouse. So, how do I run this program?

**Comment by Tenns** [comment]
any updates ?

**Comment by WhiteMagic** [comment]
No, as mentioned in other issues on UTF-8 handling, that is going to be part of r14.

**Comment by WhiteMagic** [comment]
R14 is out and should have fixed this problem.
