### ISSUE TITLE
Issue when creating curves.  

### ISSUE THREAD

**Issue by Jasond478** [WhiteMagic/JoystickGremlin#336]
When creating curves I keep getting an error and have to restart the program.   (Edit: This appears when trying to remap not creating curves)
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 274, in redraw
   File "container_plugins\basic\__init__.py", line 35, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 635, in __init__
   File "gremlin\ui\input_item.py", line 654, in _create_action_tab
   File "container_plugins\basic\__init__.py", line 49, in _create_action_ui
    widget.redraw()
   File "gremlin\ui\input_item.py", line 383, in redraw
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\remap\__init__.py", line 60, in __init__
    super().__init__(action_data, parent=parent)
   File "gremlin\ui\input_item.py", line 822, in __init__
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\remap\__init__.py", line 130, in _populate_ui
    input_name = self.type_to_name_map[input_type].lower()

**Comment by WhiteMagic** [comment]
I can think of a variety of situations that might be able to cause this, though some more information is needed to figure out what actually causes this. Can you attach the `debug.txt` file which should be located in the same folder as the Gremlin executable, as well as the `system.log` file which lives in `%userprofile%/Joystick Gremlin`. Additionally could you describe the vJoy setup being used, i.e. number of vJoy devices and their axis, buttons, and hats.

**Comment by Jasond478** [comment]
[system.log](https://github.com/WhiteMagic/JoystickGremlin/files/5612149/system.log)
[user.log](https://github.com/WhiteMagic/JoystickGremlin/files/5612150/user.log)
![Screenshot (33)](https://user-images.githubusercontent.com/26370259/100541935-3d5ae080-3215-11eb-8a90-8c2041e9531b.jpg)
vjoy is one device Screenshot of configure is included.

**Comment by WhiteMagic** [comment]
There is nothing obviously wrong with the vJoy configuration or the device detection by Gremlin, which doesn't really help in explaining what is causing the error. When you create a new profile and then add a remap does the bug still occur? Sometimes profiles have left over bits that cause grief. An other thing is does the error happen with axis inputs only or also buttons and hats?
