### ISSUE TITLE
"Unable to match vJoy devices to Windows devices" error

### ISSUE THREAD

**Issue by johnnychemo** [WhiteMagic/JoystickGremlin#346]
This error pops up for me occasionally, in this particular instance I had shut down the program a few minutes prior to restarting it and got the error. A reboot usually allows me to load it. I'm using release 13.3.

![jg error](https://user-images.githubusercontent.com/76844512/103441759-00bc4380-4c1e-11eb-9ae7-03ee8ff9a55a.png)

**Comment by WhiteMagic** [comment]
Usually, this is caused by multiple vJoy devices with identical configurations existing. However, if a reboot fixes it then it is more likely that the vJoy device is misbehaving and falsely or not at all reporting information about itself which could trigger the same error.

**Comment by ThatMBR42** [comment]
I'm receiving this error with only 1 vJoy device. I've tried reinstalling both vJoy and Joystick Gremlin, as well as rebooting, but no luck.

ETA: Reinstalled both pieces of software multiple times at this point. I'm also getting the "vJoy not running or incorrectly setup" error, so I'm going to try the debug release as mentioned in #305. The most recent error is "Unable to match vJoy devices to Windows devices," so here's the debug and log.

**Debug.txt last lines**
[2021-12-24 10:12:08.288] [debug] [info] {D21AF780-E25D-11EA-8002-444553540000}: Processing device: vJoy Device
[2021-12-24 10:12:08.294] [debug] [info] Device summary: vJoy Device {D21AF780-E25D-11EA-8002-444553540000}
[2021-12-24 10:12:08.294] [debug] [info] Axis=8 Buttons=64 Hats=1
[2021-12-24 10:12:08.294] [debug] [info] Axis map
[2021-12-24 10:12:08.294] [debug] [info]   linear=1 id=1
[2021-12-24 10:12:08.294] [debug] [info]   linear=2 id=2
[2021-12-24 10:12:08.294] [debug] [info]   linear=3 id=3
[2021-12-24 10:12:08.294] [debug] [info]   linear=4 id=4
[2021-12-24 10:12:08.294] [debug] [info]   linear=5 id=5
[2021-12-24 10:12:08.294] [debug] [info]   linear=6 id=6
[2021-12-24 10:12:08.294] [debug] [info]   linear=7 id=7
[2021-12-24 10:12:08.294] [debug] [info]   linear=8 id=8
[2021-12-24 10:12:08.294] [debug] [info] Skipping device {D21AF780-E25D-11EA-8002-444553540000}, not yet fully initialized
[2021-12-24 10:12:08.323] [debug] [info] Setting device change callback
[2021-12-24 10:12:08.323] [debug] [info] Setting event callback

**System.log for same opening attempt:**
2021-12-24 10:11:58      DEBUG --------------------------------------------------------------------------------
2021-12-24 10:11:58      DEBUG 2021-12-24 10:11
2021-12-24 10:11:58      DEBUG Starting Joystick Gremlin R13.3
2021-12-24 10:11:58      DEBUG --------------------------------------------------------------------------------
2021-12-24 10:11:59       INFO Initializing joystick devices
2021-12-24 10:11:59      DEBUG 0 joysticks detected
2021-12-24 10:11:59       INFO Checking vJoy installation
2021-12-24 10:11:59      ERROR vJoy is not present or incorrectly setup.
2021-12-24 10:11:59      ERROR vJoy is not present or incorrectly setup.

**System.log for most recent attempt:**
2021-12-24 10:45:21      DEBUG --------------------------------------------------------------------------------
2021-12-24 10:45:21      DEBUG 2021-12-24 10:45
2021-12-24 10:45:21      DEBUG Starting Joystick Gremlin R13.3
2021-12-24 10:45:21      DEBUG --------------------------------------------------------------------------------
2021-12-24 10:45:22       INFO Initializing joystick devices
2021-12-24 10:45:22      DEBUG 4 joysticks detected
2021-12-24 10:45:22      DEBUG Added: name=Thrustmaster T300RS Racing Wheel guid={E1DBDA80-05EE-11EC-8001-444553540000}
2021-12-24 10:45:22      DEBUG Added: name= VKB-Sim Gladiator NXT L   guid={045B74D0-A145-11EB-8001-444553540000}
2021-12-24 10:45:22      DEBUG Added: name=RIGHT VPC Stick WarBRD guid={8B444140-E262-11EA-8002-444553540000}
2021-12-24 10:45:22      DEBUG Added: name=TWCS Throttle guid={109ECAF0-12C9-11EA-8007-444553540000}
2021-12-24 10:45:22      DEBUG vjoy id 1: (8, 32, 1) - ERROR - vJoy device exists but DILL does not see it
2021-12-24 10:45:22      ERROR Unable to match vJoy devices to windows devices.
NoneType: None
2021-12-24 10:45:22      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1269, in <module>
   File "gremlin\joystick_handling.py", line 304, in joystick_devices_initialization
 gremlin.error.GremlinError: 'Unable to match vJoy devices to windows devices.'

**Comment by WhiteMagic** [comment]
Can't really say what's going on but it looks like for some reason Gremlin does not receive information about the vJoy devices. Either in time or at all. The debug log seems to indicate that the vJoy device is present and seen but for some reason that information never arrives in Gremlin. Some things to look at is what version of vJoy is used and if there are other programs that acquire the vJoy device which would prevent Gremlin from seeing them.
