### ISSUE TITLE
Error - can't start the progam anymore

### ISSUE THREAD

**Issue by Cop23rd** [WhiteMagic/JoystickGremlin#348]
...I can't start gremlin v13.3 anymore. Uninstall and new install don't help. Is a complete reset of joystick gremlin possible? 

2021-01-10 15:54:47      DEBUG --------------------------------------------------------------------------------
2021-01-10 15:54:47      DEBUG 2021-01-10 15:54
2021-01-10 15:54:47      DEBUG Starting Joystick Gremlin R13.3 Debug 4
2021-01-10 15:54:47      DEBUG --------------------------------------------------------------------------------
2021-01-10 15:54:48       INFO Initializing joystick devices
2021-01-10 15:54:48      DEBUG 6 joysticks detected
2021-01-10 15:54:48      DEBUG Added: name=LR guid={FD7C8F00-4BB3-11EB-8005-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=vJoy Device guid={B28B9590-4BB8-11EB-801F-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=VPC Rudder Pedals guid={FD7C8F00-4BB3-11EB-8009-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=LR guid={FD7C8F00-4BB3-11EB-8014-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=LR guid={FD8149F0-4BB3-11EB-801D-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=LR guid={C4216D10-4BB9-11EB-8020-444553540000}
2021-01-10 15:54:48      DEBUG vJoy guid={B28B9590-4BB8-11EB-801F-444553540000}: (3, 128, 0)
2021-01-10 15:54:48      DEBUG vjoy id 1: (3, 128, 0) - MATCH
2021-01-10 15:54:48       INFO Initializing joystick devices
2021-01-10 15:54:48      DEBUG 6 joysticks detected
2021-01-10 15:54:48      DEBUG Added: name=LR guid={FD7C8F00-4BB3-11EB-8005-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=vJoy Device guid={B28B9590-4BB8-11EB-801F-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=VPC Rudder Pedals guid={FD7C8F00-4BB3-11EB-8009-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=LR guid={FD7C8F00-4BB3-11EB-8014-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=LR guid={FD8149F0-4BB3-11EB-801D-444553540000}
2021-01-10 15:54:48      DEBUG Added: name=LR guid={C4216D10-4BB9-11EB-8020-444553540000}
2021-01-10 15:54:48      DEBUG Removed: name=LR guid={FD7C8F00-4BB3-11EB-8005-444553540000}
2021-01-10 15:54:48      DEBUG Removed: name=vJoy Device guid={B28B9590-4BB8-11EB-801F-444553540000}
2021-01-10 15:54:48      DEBUG Removed: name=VPC Rudder Pedals guid={FD7C8F00-4BB3-11EB-8009-444553540000}
2021-01-10 15:54:48      DEBUG Removed: name=LR guid={FD7C8F00-4BB3-11EB-8014-444553540000}
2021-01-10 15:54:48      DEBUG Removed: name=LR guid={FD8149F0-4BB3-11EB-801D-444553540000}
2021-01-10 15:54:48      DEBUG Removed: name=LR guid={C4216D10-4BB9-11EB-8020-444553540000}
2021-01-10 15:54:48      DEBUG vJoy guid={B28B9590-4BB8-11EB-801F-444553540000}: (3, 128, 0)
2021-01-10 15:54:48      DEBUG vjoy id 1: (3, 128, 0) - MATCH
2021-01-10 15:54:48       INFO Checking vJoy installation
2021-01-10 15:54:48       INFO Initializing plugins
2021-01-10 15:54:48      DEBUG Loaded: cycle-modes
2021-01-10 15:54:48      DEBUG Loaded: description
2021-01-10 15:54:48      DEBUG Loaded: macro
2021-01-10 15:54:48      DEBUG Loaded: map-to-keyboard
2021-01-10 15:54:48      DEBUG Loaded: map-to-mouse
2021-01-10 15:54:48      DEBUG Loaded: noop
2021-01-10 15:54:48      DEBUG Loaded: pause
2021-01-10 15:54:48      DEBUG Loaded: play-sound
2021-01-10 15:54:48      DEBUG Loaded: previous-mode
2021-01-10 15:54:48      DEBUG Loaded: remap
2021-01-10 15:54:48      DEBUG Loaded: response-curve
2021-01-10 15:54:48      DEBUG Loaded: resume
2021-01-10 15:54:48      DEBUG Loaded: split-axis
2021-01-10 15:54:48      DEBUG Loaded: switch-mode
2021-01-10 15:54:48      DEBUG Loaded: temporary-mode-switch
2021-01-10 15:54:48      DEBUG Loaded: text-to-speech
2021-01-10 15:54:48      DEBUG Loaded: toggle-pause
2021-01-10 15:54:48      DEBUG Loaded: basic
2021-01-10 15:54:48      DEBUG Loaded: chain
2021-01-10 15:54:48      DEBUG Loaded: double_tap
2021-01-10 15:54:48      DEBUG Loaded: hat_buttons
2021-01-10 15:54:48      DEBUG Loaded: smart_toggle
2021-01-10 15:54:48      DEBUG Loaded: tempo
2021-01-10 15:54:48      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1315, in <module>
   File "joystick_gremlin.py", line 118, in __init__
   File "joystick_gremlin.py", line 940, in _do_load_profile
   File "gremlin\profile.py", line 1458, in from_xml
   File "gremlin\profile.py", line 234, in is_current
   File "xml\etree\ElementTree.py", line 1196, in parse
   File "xml\etree\ElementTree.py", line 597, in parse
   File "<string>", line None
 xml.etree.ElementTree.ParseError: mismatched tag: line 314, column 10

**Comment by Cop23rd** [comment]
i managed to load an old profile...then the error disappeard...
