### ISSUE TITLE
UnicodeDecodeError on startup from ® in Controller Name

### ISSUE THREAD

**Issue by fetzig** [WhiteMagic/JoystickGremlin#369]
STEPS:
 * Attach [usb pedal adapter](http://www.leobodnar.com/shop/index.php?main_page=product_info&cPath=97&products_id=187&zenid=389307fa554beac0f70a341e5dd78a2e)
 * OR any other device with unicode chars in the name like said adapter `Logitech® G25 Pedals`
 * start joystick gremlin
 * crash (see logs below)

joystick gremlin stars with no issues when i detach the pedals.

confident this line needs to be fixed:
https://github.com/WhiteMagic/JoystickGremlin/blob/0e4e142d74a3eb16155b86257492528e2121605a/dill/__init__.py#L357

for nostalgia (good old python UnicodeDecodeError) I attempted to fix and rebuild the app, but your deploy.bat seems to be written just for you. Sorry for giving up so soon on sending you a proper PR. But i came up with a workaround instead (see below), that should easily help you when trying to reproduce and fix this bug.

system.log:
```
2021-06-18 20:34:53      DEBUG --------------------------------------------------------------------------------
2021-06-18 20:34:53      DEBUG 2021-06-18 20:34
2021-06-18 20:34:53      DEBUG Starting Joystick Gremlin R13.3
2021-06-18 20:34:53      DEBUG --------------------------------------------------------------------------------
2021-06-18 20:34:54       INFO Initializing joystick devices
2021-06-18 20:34:54      DEBUG 4 joysticks detected
2021-06-18 20:34:54      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1269, in <module>
   File "gremlin\joystick_handling.py", line 203, in joystick_devices_initialization
   File "dill\__init__.py", line 538, in get_device_information_by_index
   File "dill\__init__.py", line 357, in __init__
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 8: invalid start byte
```

Workaround:

Edit the name (remove the ® ) in the windows registry `HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\`. Fixes the Problem as well.

**Comment by WhiteMagic** [comment]
Yeah this is the same as #301 and as you've found out is just one place that doesn't properly do utf handling. The deploy but should easily be adjustable to your system as it should only require changing one path. Though overall this should be an easy fix when I revisit the input handling bit.

**Comment by neilser** [comment]
I've just been bitten by the very same issue (same Bodnar device). Delighted to see the registry workaround, thanks @fetzig!

**Comment by WhiteMagic** [comment]
Fixed with code that retrieves the correct system code page for decoding the name, and falls back to ignoring characters that can't be decoded in R14.
