### ISSUE TITLE
Unexpected error when running the joystick_gremlin.exe

### ISSUE THREAD

**Issue by stuart06** [WhiteMagic/JoystickGremlin#390]
I just downloaded the joystick gremlin and clicked on the joystick gremlin.exe file.  I got the following error.

Uncaught Exception:
Traceback (most recent call last)
   File "joystick_gremlin.py", line 1269 in <module>
   File "gremlin\joystick.py", line 250, in joystick.devices_initilization
 gremlin.error.Germlinerror; "indistinguishable vJoy devices present.\n\njoy
 devices have to differ in the number of (at least one of) axes, buttons, or hats in
 order to work properly with Joystick Gremlin."

I am not a programmer or technical in any way.
Do you know what I should do.

I have vjoy set up 

I have deleted joystick gremlin and vjoy and reinstalled and the same error keeps coming up.

Any help would be appreciated.

**Comment by WhiteMagic** [comment]
You're running into the same issue as described in #259
