### ISSUE TITLE
Altering virtual axis input via plugins

### ISSUE THREAD

**Issue by Ryuk47** [WhiteMagic/JoystickGremlin#394]
I am trying to create a plugin that works as a kind of moving deadzone to counter the at times unstable output of my X56 rotaries. I based this on a previous edit of yours being a moving average, however I cannot seem to find a way about "catching" the unwanted signals before they are already put out.
From my very limited understanding of Python (C# guy), I can hook onto the callback of an axis input and spawn a thread that regularly updates the value. Even with an update rate of 10 milliseconds the unwanted signal gets through still. Is there any way to alter a physical axis input before it reaches the virtual output axis?

**Comment by WhiteMagic** [comment]
I'm not really clear what you actually want to do, but some information.

- physical events are only forwarded if you instruct Gremlin to do so
- spawning a thread in response to axis input seems like a horrible idea that likely results in tons of threads fighting each other
- if you attempt to "overwrite" values cause by noise then this will never work, you will have to have a single callback that receives all physical input and decides what to do, trying to suppress, outpace, or similar ideas will not work

**Comment by Ryuk47** [comment]
So my problem is that I have a physical input that occasionally starts to jitter within a very small margin of +- 0.02, which is extremely annoying when binding it to e.g. the in-game zoom. What I would like to achieve is to have a plugin detect and smooth out this jittering before the physical input is processed to the virtual axis.

Upon another inspection of my setup I think I have identified the issue: While using the attached script to filter the physical Z axis to the virtual one, I still had the physical z axis set up to remap to the virtual z axis, so I assume my moving deadzone plugin was fighting with the remapped input. The code below now seems to do as I wished for.

```import gremlin
from gremlin.user_plugin import *


mode = ModeVariable("Mode", "The mode in which to use this mapping")

virtual_axis = VirtualInputVariable(
        "Virtual output axis",
        "The vJoy axis to send the filtered output to.",
        [gremlin.common.InputType.JoystickAxis]
)

physical_axis = PhysicalInputVariable(
        "Physical input axis",
        "The physical input axis being filtered.",
        [gremlin.common.InputType.JoystickAxis]
)

deadzone = IntegerVariable(
        "Deadzone size",
        "Size of the deadzone around the cached value.",
        5,
        0,
        100
)

# Decorator for the physical axis 
dec_physical_axis = physical_axis.create_decorator(mode.value)

# Global variables
# The cached physical input
g_cached_value = 0.0
# The current input
g_current_value = 0.0
g_vjoy = gremlin.joystick_handling.VJoyProxy()

def apply_deadzone():
    global g_current_value, g_cached_value
    if(abs(g_current_value - g_cached_value) > deadzone.value/100):
        g_cached_value = g_current_value
    return g_cached_value

def update_vjoy():
    global g_vjoy
    g_vjoy[virtual_axis.vjoy_id].axis(virtual_axis.input_id).value = apply_deadzone()

@dec_physical_axis.axis(physical_axis.input_id)
def axis_cb(event):
    global g_current_value
    g_current_value = event.value
    update_vjoy()

**Comment by mattygaga2015** [comment]
<img width="798" height="493" alt="Image" src="https://github.com/user-attachments/assets/b8bc44a9-a38f-468e-91ff-035c48e3b19e" /> I get this error when trying to use this script (or any script):

Traceback (most recent call last):
   File "gremlin\ui\script.py", line 465, in addScript
   File "gremlin\profile.py", line 1264, in add_script
   File "gremlin\user_script.py", line 411, in __init__
   File "gremlin\user_script.py", line 571, in _retrieve_variable_definitions
   File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
   File "C:\Users\matth\Joystick Gremlin\deadzone_filter.py", line 1, in <module>
    from gremlin.user_plugin import *
 ModuleNotFoundError: No module named 'gremlin.user_plugin'

**Comment by WhiteMagic** [comment]
That's to be expected since the code is trying to import modules that don't exist. Guidance on how to port R13 scripts to R14 exists in the documentation https://whitemagic.github.io/JoystickGremlin/technical/scripts.html

**Comment by mattygaga2015** [comment]
> That's to be expected since the code is trying to import modules that don't exist. Guidance on how to port R13 scripts to R14 exists in the documentation https://whitemagic.github.io/JoystickGremlin/technical/scripts.html

Brilliant thanks for this. Will this help solve ghost inputs on my X56 HOTAS? It's relentless! Thank you for this response!

**Comment by WhiteMagic** [comment]
Not sure what "this" is. If it's the script posted here maybe but also mayb not. Really depends on what "ghost inputs" means.

**Comment by mattygaga2015** [comment]
Wait, you created a program to help with ghost inputs, but dont know what ghost inputs are? I mean random button presses caused by joystick issues. Surely you knew this right?

**Comment by Ryuk47** [comment]
Hi @mattygaga2015 , while WhiteMagic is author of Joystick Gremlin, I edited the code of this plugin that I shared above (I don't remember who wrote the original script for it and would have to look it up). In the previous version of Joystick Germlin, this helped me with my own Ghost Inputs, which on my device appear to be introducing a weird jitter on the rotary axes of my X56 throttle by creating what I'd call a moving deadzobe that centers around your last given input, thereby ignoring any change in the axis unless it exceeds the deadzobe threshold.

With the rewrite to an entirely new version, this plugin will not be compatible with the latest release of Joystick Gremlin. If you wanna use this plugin as is, you would have to use the R13 version of Joystick Gremlin, or adjust the Plugin yourself in Python following the documentation shared above. I myself have been out of the flight sim sphere for a while and am not able to provide a functional update to the script at this time.
