### ISSUE TITLE
Error uncaught exception 

### ISSUE THREAD

**Issue by Averagefelineish** [WhiteMagic/JoystickGremlin#403]
Hi guys 

I am experiencing this error uncaught exception message as I hit the activate (green controller icon)
I have two 16000m and one TFRP rudder pedal in my setup.

 
![Capture](https://user-images.githubusercontent.com/80473949/173226892-5fd5894b-3071-4eb1-be82-dcfbcc6443ea.PNG)

2022-06-12 10:20:54      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\code_runner.py", line 343, in mode_changed
 IndexError: list index out of range

2022-06-12 10:33:51      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\code_runner.py", line 343, in mode_changed
 IndexError: list index out of range

could anybody able to help how to correct this please 
Thanks

**Comment by WhiteMagic** [comment]
It sounds like an issue with mode names or indices that no longer exist or similar. Though without the profile or specific information that's about as much help I can give.

**Comment by Averagefelineish** [comment]
Thanks for your replay!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
