### ISSUE TITLE
No way to rectify devices: "No device with guid exists"

### ISSUE THREAD

**Issue by brecro** [WhiteMagic/JoystickGremlin#418]
A USB interrupt occurred during regular use, and since then, Joystick Gremlin has been hung up on a missing GUID when running profiles. As a result, the profile will not run without throwing the following error with any device input:

`2022-07-21 13:14:30      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\event_handler.py", line 489, in process_event
   File "gremlin\execution_graph.py", line 76, in __call__
   File "gremlin\execution_graph.py", line 172, in process_event
   File "container_plugins\basic\__init__.py", line 123, in process_event
    return self.action_set.process_event(event, value)
   File "gremlin\execution_graph.py", line 172, in process_event
   File "gremlin\actions.py", line 119, in process_event
   File "gremlin\actions.py", line 37, in smart_all
   File "gremlin\actions.py", line 209, in __call__
   File "gremlin\input_devices.py", line 416, in __getitem__
 gremlin.error.GremlinError: 'No device with guid {6B2CBA70-ECB2-11EC-8008-444553540000} exists'

2022-07-21 13:14:30      ERROR No device with guid {6B2CBA70-ECB2-11EC-8008-444553540000} exists
NoneType: None`

Is there not a way to clear device cache? "Swap Devices" function under Actions allows me to reassign current devices, and after doing so, none of the reassigned devices share this GUID. I can't find another way to clear the missing device GUID from the program.

Thanks in advance.

**Comment by brecro** [comment]
Update: I cleared all response curves from my profile, and it no longer throws this error.
