### ISSUE TITLE
 IndexError: list index out of range

### ISSUE THREAD

**Issue by OloRatuj** [WhiteMagic/JoystickGremlin#419]
I am getting this error when activating my profile:

```
2022-08-01 02:53:59      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\code_runner.py", line 343, in mode_changed
 IndexError: list index out of range
```

Is there any limitation on the number of created event callbacks? My profile is quite big (5 physical devices, 3 vjoys) with about 150 callbacks defined.

full log below:
2022-08-01 02:46:31      DEBUG --------------------------------------------------------------------------------
2022-08-01 02:46:31      DEBUG 2022-08-01 02:46
2022-08-01 02:46:31      DEBUG Starting Joystick Gremlin R13.3
2022-08-01 02:46:31      DEBUG --------------------------------------------------------------------------------
2022-08-01 02:46:32       INFO Initializing joystick devices
2022-08-01 02:46:32      DEBUG 8 joysticks detected
2022-08-01 02:46:32      DEBUG Added: name=vJoy Device guid={BF4070B0-FA28-11EC-8002-444553540000}
2022-08-01 02:46:32      DEBUG Added: name=Throttle - HOTAS Warthog guid={DBD6B9A0-7AF9-11EB-8003-444553540000}
2022-08-01 02:46:32      DEBUG Added: name=Joystick - HOTAS Warthog guid={DBD61D60-7AF9-11EB-8001-444553540000}
2022-08-01 02:46:32      DEBUG Added: name=vJoy Device guid={85EED140-FE37-11EC-8003-444553540000}
2022-08-01 02:46:32      DEBUG Added: name=T-Rudder guid={DBD64470-7AF9-11EB-8002-444553540000}
2022-08-01 02:46:32      DEBUG Added: name=vJoy Device guid={85EED140-FE37-11EC-8005-444553540000}
2022-08-01 02:46:32      DEBUG Added: name=Arduino Micro guid={F327B400-B8BC-11EB-8001-444553540000}
2022-08-01 02:46:32      DEBUG Added: name=Pololu A-Star 32U4 guid={6F892F20-DE55-11EB-8001-444553540000}
2022-08-01 02:46:32      DEBUG vJoy guid={BF4070B0-FA28-11EC-8002-444553540000}: (8, 128, 4)
2022-08-01 02:46:32      DEBUG vJoy guid={85EED140-FE37-11EC-8003-444553540000}: (8, 128, 3)
2022-08-01 02:46:32      DEBUG vJoy guid={85EED140-FE37-11EC-8005-444553540000}: (8, 128, 2)
2022-08-01 02:46:32      DEBUG vjoy id 1: (8, 128, 4) - MATCH
2022-08-01 02:46:32      DEBUG vjoy id 2: (8, 128, 3) - MATCH
2022-08-01 02:46:32      DEBUG vjoy id 3: (8, 128, 2) - MATCH
2022-08-01 02:46:32       INFO Checking vJoy installation
2022-08-01 02:46:32       INFO Initializing plugins
2022-08-01 02:46:32      DEBUG Loaded: cycle-modes
2022-08-01 02:46:32      DEBUG Loaded: description
2022-08-01 02:46:32      DEBUG Loaded: macro
2022-08-01 02:46:32      DEBUG Loaded: map-to-keyboard
2022-08-01 02:46:32      DEBUG Loaded: map-to-mouse
2022-08-01 02:46:32      DEBUG Loaded: noop
2022-08-01 02:46:32      DEBUG Loaded: pause
2022-08-01 02:46:32      DEBUG Loaded: play-sound
2022-08-01 02:46:32      DEBUG Loaded: previous-mode
2022-08-01 02:46:32      DEBUG Loaded: remap
2022-08-01 02:46:32      DEBUG Loaded: response-curve
2022-08-01 02:46:32      DEBUG Loaded: resume
2022-08-01 02:46:32      DEBUG Loaded: split-axis
2022-08-01 02:46:32      DEBUG Loaded: switch-mode
2022-08-01 02:46:32      DEBUG Loaded: temporary-mode-switch
2022-08-01 02:46:32      DEBUG Loaded: text-to-speech
2022-08-01 02:46:32      DEBUG Loaded: toggle-pause
2022-08-01 02:46:32      DEBUG Loaded: basic
2022-08-01 02:46:32      DEBUG Loaded: chain
2022-08-01 02:46:32      DEBUG Loaded: double_tap
2022-08-01 02:46:32      DEBUG Loaded: hat_buttons
2022-08-01 02:46:32      DEBUG Loaded: smart_toggle
2022-08-01 02:46:32      DEBUG Loaded: tempo
2022-08-01 02:46:33    WARNING Unknown node present: activation-condition
2022-08-01 02:46:33    WARNING Unknown node present: activation-condition
2022-08-01 02:46:33    WARNING Unknown node present: activation-condition
2022-08-01 02:46:33       INFO Gremlin UI created
2022-08-01 02:46:33       INFO Gremlin UI launching
2022-08-01 02:46:57      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\code_runner.py", line 343, in mode_changed
 IndexError: list index out of range

**Comment by OloRatuj** [comment]
It is solved now. There was an error in vjoy axis definition in the profile xml file.
