### ISSUE TITLE
Crash on running a profile

### ISSUE THREAD

**Issue by JabberwockPL** [WhiteMagic/JoystickGremlin#46]
When I map my Saitek X45 with default Windows 7 drivers to vJoy and try to run the profile, I get the error:

Uncaught exception:
Traceback (most recent call last):
File "joystick_gremlin.py", line 271, in activate
File "gremlin\code_runner.py", line 55, in start
File "gremlin\util.py", line 569, in load_module
File "importlib\_in'rt_.py", line 109, in import_module
File "<frozen importlib._bootstrap>", line 2254, in_gcd_import
File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
File "<frozen importlib._bootstrap>", line 1129, in_exec
File "<frozen importlib._bootstrap>", line 1467, in exec_module
File "<frozen importlib._bootstrap>", line 1572, in get_code
File "<frozen importlib._bootstrap>", line 1532, in source_to_code
File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
File "C:\Users\mjarek\Joystick Gremlin\gremlin_code.py", line 40
SyntaxErron (unicode error) 'utf-8' codec can't decode byte 0xb3 in position 0:
invalid start byte

Most likely this is caused by the name assigned by the Windows Driver, it is: „6-osiowy 26-przyciskowy joystick z przełącznikiem ustawień”

**Comment by WhiteMagic** [comment]
Yeah I think this is due to the part of the code that converts device names to valid python variables doesn't know anything about utf-8 and so simply leaves those symbols. I'll have to add some UTF handling to that one I think.

If it's not too much trouble could you append the gremlin_code.py file which should be under %userprofile%/Joystick Gremlin to this issue, just so I can make sure the thing that bugs out is what I think it is.

**Comment by JabberwockPL** [comment]
I have actually found a workaround: the name of the generic controller may be changed in the registry: HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM\
then select the relevant key and change the OEMName key.

To help you with the debugging, I have switched back to the problematic name, but now I get an error about wrong / duplicate IDs. The profile runs fine, though, I do not get the first error.

Also, every time I run Joystick Gremlin, it looks like Windows is installing something, but I am not sure it is related.

**Comment by WhiteMagic** [comment]
Should be fixed with R8 due to changes in how python identifiers are generated based on the device names. The duplicate ID should now be explained better as well but is related to multiple vJoy devices being present.

As for the installing bit, Gremlin shouldn't trigger that as it isn't installing drivers etc. but maybe it triggers something odd via vJoy.
