### ISSUE TITLE
Uncaught exception on line 274

### ISSUE THREAD

**Issue by BriggsW** [WhiteMagic/JoystickGremlin#497]
Whether I select Remap, Macro, Map to Keyboard, or any other option and press add, I get the following exception

Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 274, in redraw
   File "container_plugins\basic\__init__.py", line 35, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 635, in __init__
   File "gremlin\ui\input_item.py", line 654, in _create_action_tab
   File "container_plugins\basic\__init__.py", line 49, in _create_action_ui
    widget.redraw()
   File "gremlin\ui\input_item.py", line 383, in redraw
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\remap\__init__.py", line 60, in __init__
    super().__init__(action_data, parent=parent)
   File "gremlin\ui\input_item.py", line 822, in __init__
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\remap\__init__.py", line 130, in _populate_ui
    input_name = self.type_to_name_map[input_type].lower()
 KeyError: None

If I then unselect and then select the button, axis, or hat I tried to add to, I get this error

2023-07-08 00:10:33      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 393, in input_item_selected_cb
   File "gremlin\ui\device_tab.py", line 61, in __init__
   File "gremlin\ui\device_tab.py", line 274, in redraw
   File "container_plugins\basic\__init__.py", line 35, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 635, in __init__
   File "gremlin\ui\input_item.py", line 654, in _create_action_tab
   File "container_plugins\basic\__init__.py", line 49, in _create_action_ui
    widget.redraw()
   File "gremlin\ui\input_item.py", line 383, in redraw
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\remap\__init__.py", line 60, in __init__
    super().__init__(action_data, parent=parent)
   File "gremlin\ui\input_item.py", line 822, in __init__
   File "C:\Program Files (x86)\H2ik\Joystick Gremlin\action_plugins\remap\__init__.py", line 130, in _populate_ui
    input_name = self.type_to_name_map[input_type].lower()
 KeyError: None

I've installed and uninstalled vJoy and Joystick Gemlin multiple times using the msi and zip file to no affect and will happen regardless of the vJoy config.  I've repaired and reinstalled the x86 versions of vc2010 and vc2013 and have been unable to break this pattern

**Comment by WhiteMagic** [comment]
Which version of Gremlin are you using, and what does the vJoy configuration look like? The error you're getting should not be possible as that particular failure mode is guarded against in the code.

**Comment by GregShiner** [comment]
Im getting the exact same error on version 13.3

**Comment by WhiteMagic** [comment]
Are you using 13.3 or 13.3 Debug? The latter is the one with code addressing that kind of issue.

**Comment by GregShiner** [comment]
13.3. I guess that would do it lol

**Comment by jfjago** [comment]
Well I have this error too. Have anyone found a solution ?

**Comment by atledreier** [comment]
It seems for me it's a special character in the device name that is causing it (Moza wheelbase with character 144 somewhere in there).
Haven't found a solution. The 13.3 debug just fails to  run, with no errors.

**Comment by WhiteMagic** [comment]
If the issue truly is the name of the device the registry trick to change the device name outlined in #369 might work.

**Comment by atledreier** [comment]
Yes, that trick worked, with no sideeffects that I have found so far.

For reference this was a Moza R9 Base, and the name looked ok in the registry. I deleted the full string to get rid of any hidden characters, typed in Moza R9 Base again, saved and it worked.
All the Moza software seems to work as intended after the change, so looking good so far.

**Comment by OMSKremer** [comment]
> Yes, that trick worked, with no sideeffects that I have found so far.
> 
> For reference this was a Moza R9 Base, and the name looked ok in the registry. I deleted the full string to get rid of any hidden characters, typed in Moza R9 Base again, saved and it worked. All the Moza software seems to work as intended after the change, so looking good so far.

"Same" problem here (also tested with the current .debug version). I have the Moza AB9 Base (for the new Flight Stick from Moza). I tried the mentioned workaround and renamed value via regedit for the OEMName to "Moza Base" and again "Moza AB9 Base", but that didn't help. (I also deleted the Key and created a new one)

- Moza AB9 Base
- Moza MH16 Flightstick

Possibly interesting here, I have two "Moza AB9 Base" tabs in JG, both with the same name ("Moza AB9 Base"), both differ only in that there is an additional entry “Slider” in the list for one of them.
When I open Moza Cockpit, the Moza configuration software, I only have one  to configure. (In the Windows registry there is also only 1 entry that I can identify. In HidHide, on the other hand, I can double-click/expand the “Gudsen MOZA AB9 FFB Base” and then I see two “Joystick” entries ...).

Any idea or suggestion for a workaround?

2025-02-13 14:46:13      ERROR Uncaught exception:
Traceback (most recent call last):
   File "gremlin\ui\device_tab.py", line 274, in redraw
   File "container_plugins\basic\__init__.py", line 35, in __init__
    super().__init__(profile_data, parent)
   File "gremlin\ui\input_item.py", line 635, in __init__
   File "gremlin\ui\input_item.py", line 654, in _create_action_tab
   File "container_plugins\basic\__init__.py", line 49, in _create_action_ui
    widget.redraw()
   File "gremlin\ui\input_item.py", line 383, in redraw
   File "C:\Users\s.kremer\Downloads\Joystick.Gremlin.R13.3.debug\Joystick.Gremlin.R13.3.debug\action_plugins\remap\__init__.py", line 60, in __init__
    super().__init__(action_data, parent=parent)
   File "gremlin\ui\input_item.py", line 822, in __init__
   File "C:\Users\s.kremer\Downloads\Joystick.Gremlin.R13.3.debug\Joystick.Gremlin.R13.3.debug\action_plugins\remap\__init__.py", line 134, in _populate_ui
    free_inputs = self._get_profile_root().list_unused_vjoy_inputs()
   File "gremlin\profile.py", line 1442, in list_unused_vjoy_inputs
 KeyError: 2

**Comment by WhiteMagic** [comment]
Device name encoding related issue should be gone with R14, if these issues still exist in R14 please open a new issue.
