### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by shinelith** [WhiteMagic/JoystickGremlin#509]
version 13.3

then i load profile i got a UnicodeDecodeError 

Traceback (most recent call last):
   File "joystick_gremlin.py", line 424, in load_profile
   File "joystick_gremlin.py", line 1075, in _load_recent_profile
   File "joystick_gremlin.py", line 1018, in _save_changes_request
   File "joystick_gremlin.py", line 1047, in _has_profile_changed
 UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

**Comment by WhiteMagic** [comment]
This is likely caused by the same underlying issue that causes #465 (which mentions a possible workaround) and #301.
