### ISSUE TITLE
Exception on trying to Remap Axis, Create 1:1 Mapping

### ISSUE THREAD

**Issue by chrisalleng** [WhiteMagic/JoystickGremlin#57]
Getting an exception when trying to activate a simple profile, just remapping Axis 1 from an x55 stick to vJoy device #0 axis 1.

Here's system.log:

--------------------------------------------------------------------------------
2017-06-15 19:03:15      DEBUG 2017-06-15 19:03
2017-06-15 19:03:15      DEBUG Starting Joystick Gremlin R6
2017-06-15 19:03:15      DEBUG --------------------------------------------------------------------------------
2017-06-15 19:03:15      DEBUG Loaded: cycle-modes
2017-06-15 19:03:15      DEBUG Loaded: macro
2017-06-15 19:03:15      DEBUG Loaded: pause
2017-06-15 19:03:15      DEBUG Loaded: previous-mode
2017-06-15 19:03:15      DEBUG Loaded: remap
2017-06-15 19:03:15      DEBUG Loaded: response-curve
2017-06-15 19:03:15      DEBUG Loaded: resume
2017-06-15 19:03:15      DEBUG Loaded: split-axis
2017-06-15 19:03:15      DEBUG Loaded: switch-mode
2017-06-15 19:03:15      DEBUG Loaded: text-to-speech
2017-06-15 19:03:15      DEBUG Loaded: toggle-pause
2017-06-15 19:03:19      ERROR The mode "Default" does not exist or has no associated callbacks
2017-06-15 19:03:19      ERROR The mode "None" does not exist or has no associated callbacks
2017-06-15 19:03:36      ERROR Uncaught exception:
Traceback (most recent call last):
   File "C:\Users\Chris\Joystick Gremlin\gremlin_code.py", line 17, in _mode_changed_cb
    self._handle_vjoy_0(new_mode)
   File "C:\Users\Chris\Joystick Gremlin\gremlin_code.py", line 19, in _handle_vjoy_0
    vjoy = VJoyProxy()[0]
   File "gremlin\input_devices.py", line 202, in __getitem__
   File "vjoy\vjoy.py", line 343, in __init__
 gremlin.error.VJoyError: 'Requested vJoy device is not available'

user.log has the error for attemping to create 1:1 mapping:
2017-06-15 19:07:48      DEBUG --------------------------------------------------------------------------------
2017-06-15 19:07:48      DEBUG 2017-06-15 19:07
2017-06-15 19:07:48      DEBUG Starting Joystick Gremlin R6
2017-06-15 19:07:48      DEBUG --------------------------------------------------------------------------------
2017-06-15 19:07:48      DEBUG Loaded: cycle-modes
2017-06-15 19:07:48      DEBUG Loaded: macro
2017-06-15 19:07:48      DEBUG Loaded: pause
2017-06-15 19:07:48      DEBUG Loaded: previous-mode
2017-06-15 19:07:48      DEBUG Loaded: remap
2017-06-15 19:07:48      DEBUG Loaded: response-curve
2017-06-15 19:07:48      DEBUG Loaded: resume
2017-06-15 19:07:48      DEBUG Loaded: split-axis
2017-06-15 19:07:48      DEBUG Loaded: switch-mode
2017-06-15 19:07:48      DEBUG Loaded: text-to-speech
2017-06-15 19:07:48      DEBUG Loaded: toggle-pause
2017-06-15 19:07:51      ERROR The mode "Default" does not exist or has no associated callbacks
2017-06-15 19:07:51      ERROR The mode "None" does not exist or has no associated callbacks
2017-06-15 19:07:54      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 319, in create_1to1_mapping
 KeyError: 1

OS is Windows 10 x64, and there are two physical USB Devices, the x55 stick and throttle.  One vJoy device is configured like this:
![image](https://user-images.githubusercontent.com/3527305/27205336-278c13f0-51fe-11e7-8f78-893423c9a521.png)

Please let me know if any additional info will help.
Thanks!

**Comment by chrisalleng** [comment]
Actually, to add some more detail:

I can't launch Joystick Gremlin unless I've already tried to launch it and gotten this error: 
![image](https://user-images.githubusercontent.com/3527305/27206273-6d99fb40-5204-11e7-8ee6-23b34cadb377.png)

Unless that error is open and the previous instance is still running, I'm unable to launch Joystick Gremlin and always get the error.

Thanks again!

**Comment by WhiteMagic** [comment]
The first error you get is odd, as Gremlin is attempting to grab the vJoy device with id 0 which never exists, as I make  everything start at 1 so it's nicer for people that don't write code every day. So that shouldn't ever happen.

However, the screenshot of your vJoy settings shows that you have set the hats to "4 directions", Gremlin though requires this to be "Continuous" as otherwise it's impossible to remap 8-way properly. When I change my setup to have "4 directions" I get the same error as you got in the second image. So I think a first step is to change the vJoy settings to "Continuous" and maybe that already fixes the entire problem, if not let me know.

I'll also see if I can get Gremlin to yell about the hat settings being wrong rather then the message you got which is a follow up consequence of that setting being wrong.

**Comment by chrisalleng** [comment]
Ah yes, that totally fixes the issue.  I'll try to RTFM next time around :)

Thanks again!
