### ISSUE TITLE
vJoy error

### ISSUE THREAD

**Issue by Francky63** [WhiteMagic/JoystickGremlin#83]
I uninstalled and reinstalled Joystick Gremlin and i get the below  error log, vJoy is correctly installed (i guess) and working, (tested with simple UCR config).
When i run Joystick Gremlin gave the error then JG minimize in taskbar and is not able to maximize it, i have to kill by task manager.

here the log:

2018-02-08 13:25:43      DEBUG --------------------------------------------------------------------------------
2018-02-08 13:25:43      DEBUG 2018-02-08 13:25
2018-02-08 13:25:43      DEBUG Starting Joystick Gremlin R10
2018-02-08 13:25:43      DEBUG --------------------------------------------------------------------------------
2018-02-08 13:25:43      DEBUG 3 joysticks found
2018-02-08 13:25:43      DEBUG Added: name=Thrustmaster HOTAS Cougar windows_id=2
2018-02-08 13:25:43      DEBUG Added: name=TUSBA TQS R2 windows_id=1
2018-02-08 13:25:43      DEBUG Added: name=vJoy Device windows_id=0
2018-02-08 13:25:43      DEBUG vjoy windows id 2: (1, 8, 0)
2018-02-08 13:25:43      DEBUG 3 joysticks found
2018-02-08 13:25:43      DEBUG Added: name=Thrustmaster HOTAS Cougar windows_id=2
2018-02-08 13:25:43      DEBUG Added: name=TUSBA TQS R2 windows_id=1
2018-02-08 13:25:43      DEBUG Added: name=vJoy Device windows_id=0
2018-02-08 13:25:43      DEBUG vjoy windows id 2: (1, 8, 0)
2018-02-08 13:25:43      DEBUG vjoy id 1: (1, 8, 0) - MATCH
2018-02-08 13:25:43      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      DEBUG 3 joysticks found
2018-02-08 13:25:44      DEBUG 3 joysticks found
2018-02-08 13:25:44      ERROR Requested vJoy device is not available
2018-02-08 13:25:44      DEBUG 3 joysticks found
2018-02-08 13:25:44      DEBUG Loaded: cycle-modes
2018-02-08 13:25:44      DEBUG Loaded: description
2018-02-08 13:25:44      DEBUG Loaded: macro
2018-02-08 13:25:44      DEBUG Loaded: map-to-keyboard
2018-02-08 13:25:44      DEBUG Loaded: noop
2018-02-08 13:25:44      DEBUG Loaded: pause
2018-02-08 13:25:44      DEBUG Loaded: play-sound
2018-02-08 13:25:44      DEBUG Loaded: previous-mode
2018-02-08 13:25:44      DEBUG Loaded: remap
2018-02-08 13:25:44      DEBUG Loaded: response-curve
2018-02-08 13:25:44      DEBUG Loaded: resume
2018-02-08 13:25:45      DEBUG Loaded: split-axis
2018-02-08 13:25:45      DEBUG Loaded: switch-mode
2018-02-08 13:25:45      DEBUG Loaded: temporary-mode-switch
2018-02-08 13:25:45      DEBUG Loaded: text-to-speech
2018-02-08 13:25:45      DEBUG Loaded: toggle-pause
2018-02-08 13:25:45      DEBUG Loaded: basic
2018-02-08 13:25:45      DEBUG Loaded: chain
2018-02-08 13:25:45      DEBUG Loaded: hat_buttons
2018-02-08 13:25:45      DEBUG Loaded: tempo
2018-02-08 13:25:46      DEBUG 3 joysticks found
2018-02-08 13:25:46      DEBUG 3 joysticks found
2018-02-08 13:25:46      DEBUG 3 joysticks found
2018-02-08 13:25:46      ERROR Requested vJoy device is not available
2018-02-08 13:25:46      ERROR Uncaught exception:
Traceback (most recent call last):
   File "joystick_gremlin.py", line 1262, in <module>
   File "joystick_gremlin.py", line 118, in __init__
   File "joystick_gremlin.py", line 472, in new_profile
   File "joystick_gremlin.py", line 667, in _create_tabs
   File "gremlin\ui\profile_settings.py", line 41, in __init__
   File "gremlin\ui\profile_settings.py", line 69, in _create_ui
   File "gremlin\ui\profile_settings.py", line 151, in __init__
   File "gremlin\ui\profile_settings.py", line 159, in _create_ui
   File "gremlin\joystick_handling.py", line 49, in __getitem__
   File "vjoy\vjoy.py", line 352, in __init__
 gremlin.error.VJoyError: 'Requested vJoy device is not available'

**Comment by WhiteMagic** [comment]
Is there by any chance any other program running that grabs the vJoy device? The error occurs when Gremlin attempts to obtain a vJoy device but it can't get it (vJoy devices can only be opened by a single process).

The previous attempts at grabbing the vJoy device work fine as I expect that to fail which is something I should add to the call above that fails as well. I expect the fact that it minimizes without being able to open it again is due to it crashing due to this somehow.

**Comment by Francky63** [comment]
"Is there by any chance any other program running that grabs the vJoy device? "
No, i don't think ... is there any way to check it? 
I have a script that it kill any unuseful program and service before run the sim.
What is strange is that if i run UCR after JG error UCR is able to grap vJoy but JG no.

**Comment by WhiteMagic** [comment]
The "monitor vjoy" program should be able to show you which process is holding onto which device if any. It might also be that there is a odd bug that depends on sequence / timing issues to trigger. Which might not cause any actual problem if Gremlin caught the exception properly and just ignore it, instead of just crashing.

I'll see if I can get a modified version that ensure it's not crashing in that particular call when something goes wrong as that might fix the problem.

**Comment by WhiteMagic** [comment]
Ok give this version a go https://www.dropbox.com/s/gfkm1dd35x1sdh5/Joystick.Gremlin.R10.Debug.zip?dl=0 that should not crash if the device is taken and the log should be more informative with regards to which device is taken.

**Comment by Francky63** [comment]
I cannot catch the process from vJoy monitor but i can get it from vJoyList (i guess you mean it) as i test the only PID that it try to connect to vJoy is the Joystick Gremlin PID.

Is displayed for few seconds than it is switched off. With debug version that Joystick Gremlin doesn't stuck but vJoy tab is not available...even it is reported in tools device information
vJoy - axes: 1, buttons: 8, hats: 0, system id: 2, hardware id: 305446573.

here is the log:

2018-02-11 23:30:11      DEBUG --------------------------------------------------------------------------------
2018-02-11 23:30:11      DEBUG 2018-02-11 23:30
2018-02-11 23:30:11      DEBUG Starting Joystick Gremlin R10
2018-02-11 23:30:11      DEBUG --------------------------------------------------------------------------------
2018-02-11 23:30:11      DEBUG 6 joysticks found
2018-02-11 23:30:11      DEBUG Added: name=Virtual joystick windows_id=5
2018-02-11 23:30:11      DEBUG Added: name=Thrustmaster HOTAS Cougar windows_id=4
2018-02-11 23:30:11      DEBUG Added: name=TUSBA TQS R2 windows_id=3
2018-02-11 23:30:11      DEBUG Added: name=vJoy Device windows_id=2
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 1 windows_id=1
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 2 windows_id=0
2018-02-11 23:30:11      DEBUG vjoy windows id 3: (1, 8, 0)
2018-02-11 23:30:11      DEBUG 6 joysticks found
2018-02-11 23:30:11      DEBUG Added: name=Virtual joystick windows_id=5
2018-02-11 23:30:11      DEBUG Added: name=Thrustmaster HOTAS Cougar windows_id=4
2018-02-11 23:30:11      DEBUG Added: name=TUSBA TQS R2 windows_id=3
2018-02-11 23:30:11      DEBUG Added: name=vJoy Device windows_id=2
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 1 windows_id=1
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 2 windows_id=0
2018-02-11 23:30:11      DEBUG vjoy windows id 3: (1, 8, 0)
2018-02-11 23:30:11      DEBUG vjoy id 1: (1, 8, 0) - MATCH
2018-02-11 23:30:11      ERROR Requested vJoy 1 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 2 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 2 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 3 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 3 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 4 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 4 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 5 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 5 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 6 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 6 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 7 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 7 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 8 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 8 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 9 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 9 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 10 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 10 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 11 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 11 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 12 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 12 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 13 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 13 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 14 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 14 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 15 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 15 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 16 device is not available
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      ERROR Requested vJoy 16 device is not available
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG Loaded: cycle-modes
2018-02-11 23:30:12      DEBUG Loaded: description
2018-02-11 23:30:12      DEBUG Loaded: macro
2018-02-11 23:30:12      DEBUG Loaded: map-to-keyboard
2018-02-11 23:30:12      DEBUG Loaded: noop
2018-02-11 23:30:12      DEBUG Loaded: pause
2018-02-11 23:30:12      DEBUG Loaded: play-sound
2018-02-11 23:30:12      DEBUG Loaded: previous-mode
2018-02-11 23:30:12      DEBUG Loaded: remap
2018-02-11 23:30:12      DEBUG Loaded: response-curve
2018-02-11 23:30:12      DEBUG Loaded: resume
2018-02-11 23:30:12      DEBUG Loaded: split-axis
2018-02-11 23:30:12      DEBUG Loaded: switch-mode
2018-02-11 23:30:12      DEBUG Loaded: temporary-mode-switch
2018-02-11 23:30:13      DEBUG Loaded: text-to-speech
2018-02-11 23:30:13      DEBUG Loaded: toggle-pause
2018-02-11 23:30:13      DEBUG Loaded: basic
2018-02-11 23:30:13      DEBUG Loaded: chain
2018-02-11 23:30:13      DEBUG Loaded: hat_buttons
2018-02-11 23:30:13      DEBUG Loaded: tempo
2018-02-11 23:30:13      DEBUG 6 joysticks found
2018-02-11 23:30:13      DEBUG 6 joysticks found
2018-02-11 23:30:13      ERROR Requested vJoy 0 device is not available
2018-02-11 23:30:13      DEBUG 6 joysticks found
2018-02-11 23:30:14      DEBUG 6 joysticks found
2018-02-11 23:30:14      ERROR Requested vJoy 0 device is not available

**Comment by Francky63** [comment]
I cannot catch the process from vJoy monitor but i can get it from vJoyList (i guess you mean it) as i test the only PID that it try to connect to vJoy is the Joystick Gremlin PID.

Is displayed for few seconds than it is switched off. With debug version that Joystick Gremlin doesn't stuck but vJoy tab is not available...even it is reported in tools device information
vJoy - axes: 1, buttons: 8, hats: 0, system id: 2, hardware id: 305446573.

here is the log:

2018-02-11 23:30:11      DEBUG --------------------------------------------------------------------------------
2018-02-11 23:30:11      DEBUG 2018-02-11 23:30
2018-02-11 23:30:11      DEBUG Starting Joystick Gremlin R10
2018-02-11 23:30:11      DEBUG --------------------------------------------------------------------------------
2018-02-11 23:30:11      DEBUG 6 joysticks found
2018-02-11 23:30:11      DEBUG Added: name=Virtual joystick windows_id=5
2018-02-11 23:30:11      DEBUG Added: name=Thrustmaster HOTAS Cougar windows_id=4
2018-02-11 23:30:11      DEBUG Added: name=TUSBA TQS R2 windows_id=3
2018-02-11 23:30:11      DEBUG Added: name=vJoy Device windows_id=2
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 1 windows_id=1
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 2 windows_id=0
2018-02-11 23:30:11      DEBUG vjoy windows id 3: (1, 8, 0)
2018-02-11 23:30:11      DEBUG 6 joysticks found
2018-02-11 23:30:11      DEBUG Added: name=Virtual joystick windows_id=5
2018-02-11 23:30:11      DEBUG Added: name=Thrustmaster HOTAS Cougar windows_id=4
2018-02-11 23:30:11      DEBUG Added: name=TUSBA TQS R2 windows_id=3
2018-02-11 23:30:11      DEBUG Added: name=vJoy Device windows_id=2
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 1 windows_id=1
2018-02-11 23:30:11      DEBUG Added: name=F16 MFD 2 windows_id=0
2018-02-11 23:30:11      DEBUG vjoy windows id 3: (1, 8, 0)
2018-02-11 23:30:11      DEBUG vjoy id 1: (1, 8, 0) - MATCH
2018-02-11 23:30:11      ERROR Requested vJoy 1 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 2 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 2 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 3 device is not available
2018-02-11 23:30:11      ERROR Requested vJoy 3 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 4 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 4 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 5 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 5 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 6 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 6 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 7 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 7 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 8 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 8 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 9 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 9 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 10 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 10 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 11 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 11 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 12 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 12 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 13 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 13 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 14 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 14 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 15 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 15 device is not available
2018-02-11 23:30:12      ERROR Requested vJoy 16 device is not available
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      ERROR Requested vJoy 16 device is not available
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG 6 joysticks found
2018-02-11 23:30:12      DEBUG Loaded: cycle-modes
2018-02-11 23:30:12      DEBUG Loaded: description
2018-02-11 23:30:12      DEBUG Loaded: macro
2018-02-11 23:30:12      DEBUG Loaded: map-to-keyboard
2018-02-11 23:30:12      DEBUG Loaded: noop
2018-02-11 23:30:12      DEBUG Loaded: pause
2018-02-11 23:30:12      DEBUG Loaded: play-sound
2018-02-11 23:30:12      DEBUG Loaded: previous-mode
2018-02-11 23:30:12      DEBUG Loaded: remap
2018-02-11 23:30:12      DEBUG Loaded: response-curve
2018-02-11 23:30:12      DEBUG Loaded: resume
2018-02-11 23:30:12      DEBUG Loaded: split-axis
2018-02-11 23:30:12      DEBUG Loaded: switch-mode
2018-02-11 23:30:12      DEBUG Loaded: temporary-mode-switch
2018-02-11 23:30:13      DEBUG Loaded: text-to-speech
2018-02-11 23:30:13      DEBUG Loaded: toggle-pause
2018-02-11 23:30:13      DEBUG Loaded: basic
2018-02-11 23:30:13      DEBUG Loaded: chain
2018-02-11 23:30:13      DEBUG Loaded: hat_buttons
2018-02-11 23:30:13      DEBUG Loaded: tempo
2018-02-11 23:30:13      DEBUG 6 joysticks found
2018-02-11 23:30:13      DEBUG 6 joysticks found
2018-02-11 23:30:13      ERROR Requested vJoy 0 device is not available
2018-02-11 23:30:13      DEBUG 6 joysticks found
2018-02-11 23:30:14      DEBUG 6 joysticks found
2018-02-11 23:30:14      ERROR Requested vJoy 0 device is not available

**Comment by WhiteMagic** [comment]
It seems that on your system the vJoy device often is not the first windows device. While I'm not sure that this is the actual problem it seems to be connected to it, as your last comment indicates as things seem to work when things are connected in different sequences. Btw. it seems that github again discarded your attached log files :-(

I'll try to trick my machine into giving vJoy not an id of 0 and see if doing it that way causes problems.

**Comment by Francky63** [comment]
My fault sorry... here is the link

[](https://drive.google.com/file/d/1lwFTTX26Rki8E3z9CJmaYINaQpOLcN2C/view?usp=sharing)

**Comment by Francky63** [comment]
no more problems with the debug version!

**Comment by WhiteMagic** [comment]
Good to hear, there was some other issues with how joysticks and vjoy devices were handled on startup and fixing those seems to have fixed a few other issues people have, which should all be in the next release.
